CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(12) NOT NULL,
    image VARCHAR(255),
    telegram_id BIGINT NOT NULL,
    password VARCHAR(80) NOT NULL,
    is_active boolean default true,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- constraints
    CONSTRAINT uk_user_phone UNIQUE (phone),
    CONSTRAINT uk_user_telegram_id UNIQUE (telegram_id)
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title JSONB NOT NULL DEFAULT '{}'::JSONB,
    image VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_categories_title_gin ON categories USING GIN (title);


CREATE TABLE agencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    password VARCHAR(80) NOT NULL,
    image VARCHAR(255),
    subtitle JSONB DEFAULT '{}'::JSONB,
    info JSONB DEFAULT '{}'::JSONB,
    is_active boolean default true,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     --
     -- constraints
     CONSTRAINT uk_agency_login UNIQUE (login)
);

CREATE TABLE agency_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL,
    image VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT
);


CREATE TABLE agency_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL UNIQUE,
    address TEXT,
    phone VARCHAR(12) NOT NULL,
    email VARCHAR(255) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- relations
    CONSTRAINT fk_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE
);

CREATE INDEX idx_agency_contacts_agency ON agency_contacts (agency_id);

CREATE TABLE reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    review TEXT,
    rating INTEGER CHECK (rating > 0 AND rating <= 5),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    --
    -- relations
    CONSTRAINT fk_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX idx_reviews_agency ON reviews (agency_id);


CREATE TABLE tours (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title JSONB NOT NULL,
    subtitle JSONB NOT NULL,
    address TEXT,
    max_people INTEGER NOT NULL,
    price NUMERIC(8, 2) NOT NULL,
    info JSONB DEFAULT '{}'::JSONB,
    additional_info JSONB DEFAULT '{}'::JSONB,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
    CONSTRAINT fk_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT
);

CREATE INDEX idx_tours_title_gin ON tours USING GIN (title);
CREATE INDEX idx_tours_category ON tours (category_id);
CREATE INDEX idx_tours_agency ON tours (agency_id);


CREATE TABLE tour_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL,
    image VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tour FOREIGN KEY (tour_id) REFERENCES tours(id) ON DELETE RESTRICT
);


CREATE INDEX idx_tours_images_tour ON tour_images (tour_id);


CREATE TABLE schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id BIGINT NOT NULL,
    day_number integer CHECK (day_number > 0),
    title JSONB NOT NULL,
    subtitle JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_schedules_tour_day UNIQUE (tour_id, day_number),
    CONSTRAINT fk_tour FOREIGN KEY (tour_id) REFERENCES tours(id) ON DELETE RESTRICT
);

CREATE INDEX idx_schedules_title_gin ON schedules USING GIN (title);
CREATE INDEX idx_schedules_tour ON schedules (tour_id);


CREATE TABLE inclusions (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   title JSONB NOT NULL,
   tour_id BIGINT NOT NULL,
   is_included boolean default true,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   --
   -- relations
   CONSTRAINT fk_tour FOREIGN KEY (tour_id) REFERENCES tours(id) ON DELETE RESTRICT
);

CREATE INDEX idx_inclusions_tour ON inclusions (tour_id);


CREATE TABLE applications (
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   tour_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL,

   full_name VARCHAR(255) NOT NULL,
   phone VARCHAR(12) NOT NULL,
   email VARCHAR(255) NOT NULL,
   person_count INTEGER NOT NULL CHECK(person_count > 0),
   total_price NUMERIC(8, 2) NOT NULL,

   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   --
   -- relations
   CONSTRAINT fk_tour FOREIGN KEY (tour_id) REFERENCES tours(id) ON DELETE RESTRICT,
   CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);


CREATE TYPE user_role_enum AS ENUM (
    'USER',
    'AGENCY',
    'ADMIN'
);


CREATE TABLE refresh_token_entity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token varchar(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP WITH TIME ZONE,
    subject VARCHAR(255) NOT NULL,
    user_role user_role_enum NOT NULL
);



